# Generated by Django 3.0.3 on 2020-02-27 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, default='empty', max_length=200)),
                ('answer', models.CharField(default='Emtpy', max_length=200)),
                ('category', models.CharField(choices=[('1', 'Sports'), ('2', 'Music'), ('3', 'Movies'), ('4', 'Pop Culture')], default='Pick one', max_length=50)),
                ('type', models.CharField(choices=[('1', 'Multiple Choice'), ('2', 'True/False')], default='Pick one', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trivia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='Title of Game', max_length=200)),
                ('category', models.CharField(choices=[('1', 'Sports'), ('2', 'Music'), ('3', 'Movies'), ('4', 'Pop Culture')], default='Pick one', max_length=50)),
                ('type', models.CharField(choices=[('1', 'Multiple Choice'), ('2', 'True/False')], default='Pick one', max_length=50)),
            ],
        ),
    ]
