# Generated by Django 2.2.1 on 2020-02-18 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0002_auto_20200218_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='difficulty',
        ),
        migrations.AddField(
            model_name='trivia',
            name='genre',
            field=models.CharField(choices=[('1', 'Sports'), ('2', 'Music'), ('3', 'Movies'), ('4', 'Pop Culture')], default='Pick one', max_length=50),
        ),
        migrations.AddField(
            model_name='trivia',
            name='title',
            field=models.CharField(default='Title of Game', max_length=200),
        ),
        migrations.AddField(
            model_name='trivia',
            name='type',
            field=models.CharField(choices=[('1', 'Multiple Choice'), ('2', 'True/False')], default='Pick one', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(default='Emtpy', max_length=200),
        ),
        migrations.RemoveField(
            model_name='question',
            name='game',
        ),
        migrations.AddField(
            model_name='question',
            name='game',
            field=models.ManyToManyField(to='trivia.Trivia'),
        ),
        migrations.AlterField(
            model_name='question',
            name='genre',
            field=models.CharField(choices=[('1', 'Sports'), ('2', 'Music'), ('3', 'Movies'), ('4', 'Pop Culture')], default='Pick one', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('1', 'Multiple Choice'), ('2', 'True/False')], default='Pick one', max_length=50),
        ),
        migrations.AlterField(
            model_name='trivia',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='empty', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
